Revert "Add version info & config file path in settings form" Cause `java.lang.NoSuchMethodError: com.intellij.openapi.components.impl.stores.IComponentStore.getStateStorageManager()Lcom/intellij/configurationStore/StateStorageManager;` on intellij 2018 and above
This reverts commit 65cd2ebe3b6ce7ffecaf8fc1b2dd270fc8bef72a.